services:
  postgres_source:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.postgres.source
    container_name: postgres_source
    env_file:
      - .source.env
    ports:
      - '4444:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./compose/postgres_source.conf:/etc/postgresql/postgresql.custom.conf:ro
      - ./compose/postgres_source_init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command:
      ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.custom.conf']
    networks:
      - source-net

  flyway:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.flyway
    container_name: flyway
    depends_on:
      - postgres_source
    env_file:
      - .source.env
    volumes:
      - ./migrations:/flyway/sql
    command: migrate
    networks:
      - source-net

  seeder:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.fastapi.seeder
    container_name: seeder
    depends_on:
      - postgres_source
    env_file:
      - .source.env
    ports:
      - '8000:8000'
    volumes:
      - ./seeder:/app
    command: fastapi dev --host 0.0.0.0 --port 8000
    networks:
      - source-net

volumes:
  postgres-data:

networks:
  source-net:
    driver: bridge
