services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - "4444:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  flyway:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.flyway
    container_name: flyway
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./migrations:/flyway/sql
    command: migrate

  seeder:
      build:
        context: .
        dockerfile: ./compose/Dockerfile.fastapi.seeder
      container_name: seeder
      depends_on:
        - postgres
      env_file:
        - .env
      ports:
        - "8000:8000"
      volumes:
        - ./seeder:/app
      command: fastapi dev --host 0.0.0.0 --port 8000

volumes:
  postgres-data:
