services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - "4444:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  flyway:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.flyway
    container_name: flyway
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./migrations:/flyway/sql
    command: migrate

volumes:
  postgres-data:
