services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.postgres.source
    container_name: postgres_source
    env_file:
      - .source.env
    ports:
      - '4444:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./compose/postgres_source_init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  flyway:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.flyway
    container_name: flyway
    depends_on:
      - postgres
    env_file:
      - .source.env
    volumes:
      - ./migrations:/flyway/sql
    command: migrate

  seeder:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.fastapi.seeder
    container_name: seeder
    depends_on:
      - postgres
    env_file:
      - .source.env
    ports:
      - '8000:8000'
    volumes:
      - ./seeder:/app
    command: fastapi dev --host 0.0.0.0 --port 8000

volumes:
  postgres-data:
