services:
  minio:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.minio
    container_name: minio
    env_file:
      - .lake.env
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - lake-net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 10s
      timeout: 5s
      retries: 5

  mc:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.miniomc
    container_name: mc
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - .lake.env
    networks:
      - lake-net

volumes:
  minio-data:

networks:
  lake-net:
    driver: bridge
