FROM confluentinc/cp-kafka-connect:7.8.2

# https://debezium.io/releases/
ENV DEBEZIUM_VERSION=3.0.8.Final
ENV CONNECT_PLUGIN_PATH=/usr/share/java

RUN mkdir -p /usr/share/java/debezium-connector-postgresql && \
    curl -L https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/${DEBEZIUM_VERSION}/debezium-connector-postgres-${DEBEZIUM_VERSION}-plugin.tar.gz \
    | tar -xz -C /usr/share/java/debezium-connector-postgresql --strip-components=1
