FROM confluentinc/cp-kafka-connect:7.8.2

ENV CONNECT_PLUGIN_PATH=/usr/share/java

USER root
RUN microdnf install -y unzip
USER appuser

# Debezium Postgres connector
ENV DEBEZIUM_VERSION=2.5.4
RUN mkdir -p /usr/share/java/debezium-connector-postgresql && \
    curl -L https://hub-downloads.confluent.io/api/plugins/debezium/debezium-connector-postgresql/versions/${DEBEZIUM_VERSION}/debezium-debezium-connector-postgresql-${DEBEZIUM_VERSION}.zip -o /tmp/debezium.zip && \
    unzip /tmp/debezium.zip -d /usr/share/java/debezium-connector-postgresql && \
    rm /tmp/debezium.zip
